//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDijkstra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Flight
    {
        public string TicketNo { get; set; }
        public string FlightNo { get; set; }
        public int SequenceNo { get; set; }
        public bool IsReturn { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
