//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.RoutesAsOriginal = new HashSet<Route>();
            this.Routes1 = new HashSet<Route>();
        }
    
        public string CityID { get; set; }
        public string CityName { get; set; }
        public bool InService { get; set; }
    
        public virtual ICollection<Route> RoutesAsOriginal { get; set; }
        public virtual ICollection<Route> Routes1 { get; set; }
    }
}
