//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Seats = new HashSet<Seat>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
