//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.TakenSeats = new HashSet<TakenSeat>();
            this.Ticket_Flight = new HashSet<Ticket_Flight>();
        }
    
        public string FlightNo { get; set; }
        public decimal CurrentPrice { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public int RouteID { get; set; }
        public double Duration { get; set; }
        public double CancellationFee { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual ICollection<TakenSeat> TakenSeats { get; set; }
        public virtual ICollection<Ticket_Flight> Ticket_Flight { get; set; }
    }
}
